### ISSUE TITLE
what changes should be made if I want to use hg19?

### ISSUE THREAD

**Issue by fangli08** [gatk-workflows/broad-prod-wgs-germline-snps-indels#12]
Hi, 

From the readme file, I learned that the reference genome must be Hg38 with ALT contigs. What changes should be made if I want to use hg19 (in addition to changing the reference FASTA file, indexing the FASTA file)? Because right now, a lot of databases are based on hg19. 

Thank you! 
Li

**Comment by bshifaw** [comment]
The following material is provided by the GATK Team. Please post any questions or concerns to one of our forum sites : [GATK](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team/) , [FireCloud](https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team) or [Terra](https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500432-General-Discussion) , [WDL/Cromwell](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team).

You can try looking at the [PairedEndSingleSampleWf-fc-b37.wdl](https://github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels).
