### ISSUE TITLE
PairedEndSingleSampleWf.wdl is not portable

### ISSUE THREAD

**Issue by geoffjentry** [gatk-workflows/broad-prod-wgs-germline-snps-indels#14]
`String sub_strip_path = "gs://.*/"` should be replaced with usages of `basename()`. At the moment this workflow can not run with S3, etc

**Comment by bshifaw** [comment]
Looks like this was done before for the [five-dollar workflow](https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline/pull/7/commits/71e45ba50fd8b370a2dfd5766db6617167c9c864), I'll use this as reference to make the change.

**Comment by geoffjentry** [comment]
Exactly the case, thanks @bshifaw
