### ISSUE TITLE
Most up to date WGS pipeline

### ISSUE THREAD

**Issue by gevro** [gatk-workflows/broad-prod-wgs-germline-snps-indels#16]
Hi,
Why is this workflow still using GATK3 for haplotype caller and beta versions of GATK4 for other parts of the workflow? Is this workflow being maintained? It appears quite out of date in terms of tools. Is there another workflow that is better for WGS SNV/Indel analysis than this out of date workflow?

Thanks.

**Comment by vdauwera** [comment]
This workflow has been replaced by https://github.com/gatk-workflows/five-dollar-genome-analysis-pipeline (added a note in the repo description, also noted in the readme)
