### ISSUE TITLE
BucketNotFoundException: 404 for empty.vcf

### ISSUE THREAD

**Issue by shkao** [gatk-workflows/broad-prod-wgs-germline-snps-indels#2]
Hi,

In [line 43 of PairedEndSingleSampleWf.hg38.inputs.json](https://github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels/blob/082f16ffb5d354c99b575fde5e98e28e95265ade/PairedEndSingleSampleWf.hg38.inputs.json#L43): `"##PairedEndSingleSampleWorkflow.haplotype_database_file": "gs://gatk-aas-test-data/small/empty.vcf",`

Not sure if it's critical, I found it not existing in the gs:
```
gsutil ls gs://gatk-aas-test-data/small/empty.vcf
BucketNotFoundException: 404 gs://gatk-aas-test-data bucket does not exist.
```

**Comment by bshifaw** [comment]
The json file has been updated to mark that variable as optional and remove the empty vcf.
Thanks

**Comment by shkao** [comment]
I see, thanks!
