### ISSUE TITLE
/cromwell_root/exec.sh: line 30: /usr/gitc/gatk-launch: No such file or directory

### ISSUE THREAD

**Issue by mbookman** [gatk-workflows/broad-prod-wgs-germline-snps-indels#6]
The JointGenotypingWf.wdl + JointGenotypingWf.options.json here fails to run successfully.
The call-ImportGVCFs step fails with:

    /cromwell_root/exec.sh: line 30: /usr/gitc/gatk-launch: No such file or directory

There seems to be a mismatch between the command and the Docker image.

The options file contains:

    "docker": "broadinstitute/genomes-in-the-cloud:2.3.1-1504795437"

The WDL contains calls to:

    /usr/gitc/gatk-launch --javaOptions "-Xmx4g -Xms4g" \

throughout. But `gatk-launch` does not exist:

```
$ docker run --rm -t -i broadinstitute/genomes-in-the-cloud:2.3.1-1504795437 /bin/bash
<snip>
Digest: sha256:9f71a51db037076aeaf262b96e7adbeb5dec02f1dc4af83454befa9508303a54
Status: Downloaded newer image for broadinstitute/genomes-in-the-cloud:2.3.1-1504795437
root@dffac261c37f:/usr/gitc# ls
Dockerfile  GATK35.jar	bgzip  gatk4	   svtoolkit2.00
GATK34.jar  GATK36.jar	bwa    picard.jar  tabix
```

**Comment by bshifaw** [comment]
Hi Matt,
The wdl is using a private docker image and there isn't a public version made available in broadinsitute/ yet. I've made a temporary docker image that can be used to work with the latest release of the JointGenotypingWF.wdl which uses gatk4.0.1.0. 
bshifaw/gatk4.0.1.0-joint-genotyping

**Comment by mbookman** [comment]
Thanks @bshifaw!

@ldgauthier pointed me to https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4.wdl, which fit what I needed.
