### ISSUE TITLE
ERROR: Status of job is not Submitted, Running, or Succeeded: Failed (Header version: 1.6)

### ISSUE THREAD

**Issue by ScottMcCormack** [gatk-workflows/broad-prod-wgs-germline-snps-indels#9]
I'm currently following along with the following example on Google Cloud Platform that uses this repository: [Running a GATK Best Practices Pipeline](https://cloud.google.com/genomics/docs/tutorials/gatk)

Following along with the tutorial successfully executes the pipeline but it appears to fail when running the `call-ValidateCram` step. The following files are outputted at this step:

**NA12878.cram.validation_report**
```
ERROR: Header version: 1.6 does not match any of the acceptable versions: 1.0, 1.3, 1.4, 1.5
```

**ValidateCram.log** and **stderr**
```
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.557683f7
10:14:09.328 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/gitc/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Feb 13 10:14:09 UTC 2019] ValidateSamFile INPUT=/cromwell_root/mgd-gatk-demo/work/PairedEndSingleSampleWorkflow/d6955615-8347-4760-92b5-43747a0e3002/call-ConvertToCram/NA12878.cram OUTPUT=NA12878.cram.validation_report MODE=VERBOSE IGNORE=[MISSING_TAG_NM] MAX_OUTPUT=1000000000 IS_BISULFITE_SEQUENCED=false SKIP_MATE_VALIDATION=false REFERENCE_SEQUENCE=/cromwell_root/broad-references/hg38/v0/Homo_sapiens_assembly38.fasta    IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE MAX_OPEN_TEMP_FILES=8000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Feb 13 10:14:09 UTC 2019] Executing as root@2cb927dcf8d1 on Linux 4.14.74+ amd64; OpenJDK 64-Bit Server VM 1.8.0_111-8u111-b14-2~bpo8+1-b14; Deflater: Intel; Inflater: Intel; Picard version: 2.16.0-SNAPSHOT
WARNING	2019-02-13 10:14:10	CRAMFileReader	CRAM index file /cromwell_root/mgd-gatk-demo/work/PairedEndSingleSampleWorkflow/d6955615-8347-4760-92b5-43747a0e3002/call-ConvertToCram/NA12878.cram.crai is older than CRAM /cromwell_root/mgd-gatk-demo/work/PairedEndSingleSampleWorkflow/d6955615-8347-4760-92b5-43747a0e3002/call-ConvertToCram/NA12878.cram
[Wed Feb 13 10:14:53 UTC 2019] picard.sam.ValidateSamFile done. Elapsed time: 0.73 minutes.
Runtime.totalMemory()=6029312000
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
```
The end of **logging_output** gives the same error
```
 Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp.557683f7
10:14:09.328 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/gitc/picard.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Feb 13 10:14:09 UTC 2019] ValidateSamFile INPUT=/cromwell_root/mgd-gatk-demo/work/PairedEndSingleSampleWorkflow/d6955615-8347-4760-92b5-43747a0e3002/call-ConvertToCram/NA12878.cram OUTPUT=NA12878.cram.validation_report MODE=VERBOSE IGNORE=[MISSING_TAG_NM] MAX_OUTPUT=1000000000 IS_BISULFITE_SEQUENCED=false SKIP_MATE_VALIDATION=false REFERENCE_SEQUENCE=/cromwell_root/broad-references/hg38/v0/Homo_sapiens_assembly38.fasta    IGNORE_WARNINGS=false VALIDATE_INDEX=true INDEX_VALIDATION_STRINGENCY=EXHAUSTIVE MAX_OPEN_TEMP_FILES=8000 VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Wed Feb 13 10:14:09 UTC 2019] Executing as root@2cb927dcf8d1 on Linux 4.14.74+ amd64; OpenJDK 64-Bit Server VM 1.8.0_111-8u111-b14-2~bpo8+1-b14; Deflater: Intel; Inflater: Intel; Picard version: 2.16.0-SNAPSHOT
WARNING	2019-02-13 10:14:10	CRAMFileReader	CRAM index file /cromwell_root/mgd-gatk-demo/work/PairedEndSingleSampleWorkflow/d6955615-8347-4760-92b5-43747a0e3002/call-ConvertToCram/NA12878.cram.crai is older than CRAM /cromwell_root/mgd-gatk-demo/work/PairedEndSingleSampleWorkflow/d6955615-8347-4760-92b5-43747a0e3002/call-ConvertToCram/NA12878.cram
[Wed Feb 13 10:14:53 UTC 2019] picard.sam.ValidateSamFile done. Elapsed time: 0.73 minutes.
Runtime.totalMemory()=6029312000
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp

2019-02-13 10:25:59,998 cromwell-system-akka.dispatchers.engine-dispatcher-26 INFO  - WorkflowManagerActor WorkflowActor-d6955615-8347-4760-92b5-43747a0e3002 is in a terminal state: WorkflowFailedState
ERROR: Status of job is not Submitted, Running, or Succeeded: Failed
```
From a bit of research its looks as though it could possibly be related to the following links:
- https://www.biostars.org/p/337453/
- https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/samtools/SAMFileHeader.java#L52

**Note**: The tutorial asks to modify `PairedEndSingleSampleWf.gatk4.0.options.json` to use `"docker": "broadinstitute/gatk:latest"` instead of `"docker": "broadinstitute/gatk:4.0.0.0"` (not sure if this is related)

Could you advise how I can rectify this issue? 

**Disclaimer**: I'm unsure if this is an issue related to this repository or the wdl-runner repository (https://github.com/broadinstitute/wdl-runner) that is used with this code.

**Comment by bshifaw** [comment]
The following material is made available by the GATK Team. Please post any questions or concerns to one of our forum sites : [GATK](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team/) , [FireCloud](https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team) , [WDL/Cromwell](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team).

Try running with the provided docker tag version in the option file.

**Comment by ScottMcCormack** [comment]
Ok thanks, I'll post to these forums instead and update this issue when I find a solution.

I tried running with `"docker": "broadinstitute/gatk:4.0.0.0"` and still had the same issue

**Comment by bshifaw** [comment]
https://github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels/blob/5585cdf7877104f2c61b2720ddfe7235f2fad577/PairedEndSingleSampleWf.options.json#L5

**Comment by ScottMcCormack** [comment]
> [broad-prod-wgs-germline-snps-indels/PairedEndSingleSampleWf.options.json](https://github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels/blob/5585cdf7877104f2c61b2720ddfe7235f2fad577/PairedEndSingleSampleWf.options.json#L5)
> 
> Line 5 in [5585cdf](/gatk-workflows/broad-prod-wgs-germline-snps-indels/commit/5585cdf7877104f2c61b2720ddfe7235f2fad577)
> 
>  "docker": "broadinstitute/genomes-in-the-cloud:2.3.1-1512499786"

Should I substitute the the following line with `"docker": "broadinstitute/genomes-in-the-cloud:2.3.1-1512499786"`?

https://github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels/blob/master/PairedEndSingleSampleWf.gatk4.0.options.json#L5

**Comment by bshifaw** [comment]
yes
